services:
  # DrupalConsoleLauncher Services
  console.launcher:
    class: Drupal\Console\Launcher\Utils\Launcher
  console.launcher_remote:
    class: Drupal\Console\Launcher\Utils\LauncherRemote
  # DrupalConsoleLauncher Commands
  console.self_update:
    class: Drupal\Console\Launcher\Command\Self\UpdateCommand
    tags:
      - { name: drupal.command }