services:
  # DrupalConsoleLauncher Services
  console.launcher:
    class: Drupal\ConsoleLauncher\Utils\Launcher
  # DrupalConsoleLauncher Commands
  console.self_update:
    class: Drupal\ConsoleLauncher\Command\Self\UpdateCommand
    tags:
      - { name: drupal.command }
