services:
  # DrupalConsoleLauncher Services
  console.launcher:
    class: Drupal\Console\Utils\Launcher
  # DrupalConsoleLauncher Commands
  console.self_update:
    class: Drupal\Console\Command\Self\UpdateCommand
    tags:
      - { name: drupal.command }
  console.site_new:
    class: Drupal\Console\Command\Site\NewCommand
    arguments: ['@console.shell_process']
    tags:
      - { name: drupal.command }
